language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - \[ "$TRAVIS_PHP_VERSION" == "7.0" \] && echo "xdebug.overload_var_dump = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - make test

